name: initialize-manager
description: "Setups the manager instance and firesim repo"

inputs:
  max-runtime-hours:
    description: "Max runtime hours"
    required: true

runs:
  using: "composite"
  steps:
    - run: .github/scripts/initialize-manager.py ${{ inputs.max-runtime-hours }}
      shell: bash
