version: 2

updates:
  # submit a PR for bumping submodules daily (for all submodules).
  # updates a submodule to the latest commit on the branch given in .gitmodules.
  # if branch not given, then it defaults to the main/master branch.
  - package-ecosystem: gitsubmodule
    schedule:
      interval: "daily"
    directory: /
