### Build Farm Config File ###

###########
# Schema:
###########
# # Unique name for build farm. Build farm named "default-build-farm" will
# # be the default build farm used for all recipes without a specific build
# # farm used.
# <NAME>:
#     # Human readable name of the build farm type.
#     # This can be determined from the `NAME` field in `BuildFarmHostDispatcher`
#     # child class (located in `deploy/buildfarmhostdispatcher.py`).
#     build-farm-type: <TYPE NAME>
#     args:
#         # Build farm arguments that are passed to the `BuildFarmHostDispatcher`
#         # object. Determined by looking at `parse_args` function of class.
#         <K/V pairs of args>

# THIS WILL BE USED IF BUILDFARM NOT SPECIFIED IN RECIPE
# Note: For large designs (ones that would fill a EC2.2xlarge/Xilinx VU9P)
# Vivado uses in excess of 32 GiB. Keep this in mind when selecting a
# non-default instance type.
default-build-farm:
    build-farm-type: aws-ec2
    args:
        # REQUIRED: instance type to use per build
        instance-type: z1d.2xlarge
        # REQUIRED: instance market to use per build
        build-instance-market: ondemand
        # REQUIRED: if using spot instances, determine the interrupt behavior
        spot-interruption-behavior: terminate
        # REQUIRED: if using spot instances, determine the max price
        spot-max-price: ondemand
        # OPTIONAL: change location of build directory on build host.
        # defaults to `$HOME/firesim-build`.
        build-dir: null

# Unmanaged list of build hosts. Assumed that they are pre-setup to run builds.
local-build-farm:
    build-farm-type: unmanaged
    args:
        # OPTIONAL: Change location of build directory on build host.
        # defaults to `$HOME/firesim-build`.
        default-build-dir: null
        # REQUIRED: List of IP addresses (or "localhost"). Each can have an optional
        # argument specifying to override the default build directory.
        #
        # Ex:
        # build-farm-hosts:
        #     # use localhost and don't override the default build dir
        #     - localhost
        #     # use other IP address (don't override default build dir)
        #     - "111.111.1.111"
        #     # use other IP address (override default build dir for this build host)
        #     - "222.222.2.222":
        #         override-build-dir: /scratch/specific-build-host-build-dir
        build-farm-hosts:
            - localhost
