# Hardware config database for FireSim Simulation Manager
# See https://docs.fires.im/en/stable/Advanced-Usage/Manager/Manager-Configuration-Files.html for documentation of all of these params.

# Hardware configs represent a combination of an agfi, a deployquintuplet override
# (if needed), and a custom runtime config (if needed)

# The AGFIs provided below are public and available to all users.
# Only AGFIs for the latest release of FireSim are guaranteed to be available.
# If you are using an older version of FireSim, you will need to generate your
# own images.

# DOCREF START: Example HWDB Entry
firesim_boom_singlecore_nic_l2_llc4mb_ddr3:
    agfi: agfi-0292ea4a6e8116287
    deploy_quintuplet_override: null
    custom_runtime_config: null
# DOCREF END: Example HWDB Entry
firesim_boom_singlecore_no_nic_l2_llc4mb_ddr3:
    agfi: agfi-01fbe08cbc6208366
    deploy_quintuplet_override: null
    custom_runtime_config: null
firesim_gemmini_printf_rocket_singlecore_no_nic:
    agfi: agfi-0c15946be9bfc2c48
    deploy_quintuplet_override: null
    custom_runtime_config: null
firesim_gemmini_rocket_singlecore_no_nic:
    agfi: agfi-0dc78322bfb382604
    deploy_quintuplet_override: null
    custom_runtime_config: null
firesim_rocket_quadcore_nic_l2_llc4mb_ddr3:
    agfi: agfi-0a6c111c586e3d00f
    deploy_quintuplet_override: null
    custom_runtime_config: null
firesim_rocket_quadcore_no_nic_l2_llc4mb_ddr3:
    agfi: agfi-071c84f073ec12786
    deploy_quintuplet_override: null
    custom_runtime_config: null
firesim_rocket_singlecore_no_nic_l2_lbp:
    agfi: agfi-012479b511e2e2841
    deploy_quintuplet_override: null
    custom_runtime_config: null
firesim_rocket_singlecore_sha3_nic_l2_llc4mb_ddr3:
    agfi: agfi-0269d5f8cf362680f
    deploy_quintuplet_override: null
    custom_runtime_config: null
firesim_rocket_singlecore_sha3_no_nic_l2_llc4mb_ddr3:
    agfi: agfi-04ac4491551142bc2
    deploy_quintuplet_override: null
    custom_runtime_config: null
firesim_rocket_singlecore_sha3_no_nic_l2_llc4mb_ddr3_printf:
    agfi: agfi-010978fdc38c83f59
    deploy_quintuplet_override: null
    custom_runtime_config: null
firesim_supernode_rocket_singlecore_nic_l2_lbp:
    agfi: agfi-029c99bc6f4781d1c
    deploy_quintuplet_override: null
    custom_runtime_config: null
vitis_firesim_rocket_singlecore_no_nic:
    xclbin: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/6ceb4e383e7273c5301ac62810aced72cf0b5ddd/vitis/vitis_firesim_rocket_singlecore_no_nic.xclbin
    deploy_quintuplet_override: vitis-firesim-FireSim-FireSimRocketMMIOOnlyConfig-BaseVitisConfig
    custom_runtime_config: null
vitis_firesim_gemmini_rocket_singlecore_no_nic:
    xclbin: https://raw.githubusercontent.com/firesim/firesim-public-bitstreams/c49ee9ae58115ab04fde2ffa4c1ed08dfb5caed0/vitis/vitis_firesim_gemmini_rocket_singlecore_no_nic.xclbin
    deploy_quintuplet_override: vitis-firesim-FireSim-FireSimLeanGemminiRocketMMIOOnlyConfig-BaseVitisConfig
    custom_runtime_config: null
# DOCREF START: Xilinx Alveo HWDB Entries
alveo_u250_firesim_rocket_singlecore_no_nic:
    bitstream_tar: REPLACE_THIS
    deploy_quintuplet_override: null
    custom_runtime_config: null
alveo_u280_firesim_rocket_singlecore_no_nic:
    bitstream_tar: REPLACE_THIS
    deploy_quintuplet_override: null
    custom_runtime_config: null
# DOCREF END: Xilinx Alveo HWDB Entries
