### Build Farm ###

# THIS WILL BE USED IF BUILDFARM NOT SPECIFIED IN RECIPE
# Note: For large designs (ones that would fill a EC2.2xlarge/Xilinx VU9P)
# Vivado uses in excess of 32 GiB. Keep this in mind when selecting a
# non-default instance type.
default-build-farm:
    build-farm-type: aws-ec2
    args:
        instance-type: z1d.2xlarge
        build-instance-market: ondemand
        spot-interruption-behavior: terminate
        spot-max-price: ondemand
        # change location of build on build host
        build-dir: null

local-build-farm:
    build-farm-type: unmanaged
    args:
        default-build-dir: null
        build-farm-hosts:
            - localhost
                # change location of build on build host (abs. path)
                override-build-dir: null
