# RUNTIME configuration for the FireSim Simulation Manager
# See docs/Advanced-Usage/Manager/Manager-Configuration-Files.rst for
# documentation of all of these params.

run-farm:
    run-farm-tag: mainrunfarm
    f1_16xlarges: 1
    m4_16xlarges: 0
    f1_4xlarges: 0
    f1_2xlarges: 0
    run-instance-market: ondemand
    spot-interruption-behavior: terminate
    spot-max-price: ondemand

target-config:
    # Set topology: no_net_config to run without a network simulation
    topology: example_8config
    no-net-num-nodes: 2
    link-latency: 6405
    switching-latency: 10
    net-bandwidth: 200
    profile-interval: -1

    # This references a section from config_build_recipes.yaml
    # In homogeneous configurations, use this to set the hardware config deployed
    # for all simulators
    default-hw-config: firesim-rocket-quadcore-nic-l2-llc4mb-ddr3

tracing:
    enable: no

    # Trace output formats. Only enabled if "enable" is set to "yes" above
    # 0 = human readable; 1 = binary (compressed raw data); 2 = flamegraph (stack
    # unwinding -> Flame Graph)
    output-format: 0

    # Trigger selector.
    # 0 = no trigger; 1 = cycle count trigger; 2 = program counter trigger; 3 =
    # instruction trigger
    selector: 1
    start: 0
    end: -1

autocounter:
    read-rate: 0

workload:
    workload-name: linux-uniform.json
    terminate-on-completion: no
    suffix-tag: null

host-debug:
    # When enabled (=yes), Zeros-out FPGA-attached DRAM before simulations
    # begin (takes 2-5 minutes).
    # In general, this is not required to produce deterministic simulations on
    # target machines running linux. Enable if you observe simulation non-determinism.
    zero-out-dram: no
    # If disable-synth-asserts: no, simulation will print assertion message and
    # terminate simulation if synthesized assertion fires.
    # If disable-synth-asserts: yes, simulation ignores assertion firing and
    # continues simulation.
    disable-synth-asserts: no

synth-print:
    # Start and end cycles for outputting synthesized prints.
    # They are given in terms of the base clock and will be converted
    # for each clock domain.
    start: 0
    end: -1
    # When enabled (=yes), prefix print output with the target cycle at which the print was triggered
    cycle-prefix: yes
