name: repo-setup-aws
description: "Runs all baseline setup to interact with a AWS-hosted manager instance"

runs:
  using: "composite"
  steps:
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - uses: ./.github/actions/install-ci-python-reqs
