run_farm_config:
  defaults: sample-run-farm-recipes/aws_ec2.yaml
  override_args:
    run_farm_tag: bwtest-mainrunfarm
    run_farm_hosts:
      - f1.16xlarge: 2
      - f1.4xlarge: 0
      - f1.2xlarge: 0
      - m4.16xlarge: 1

target_config:
    topology: example_16config
    no_net_num_nodes: 2
    link_latency: 6405
    switching_latency: 10
    net_bandwidth: 200
    profile_interval: -1
    default_hw_config: firesim_rocket_quadcore_nic_l2_llc4mb_ddr3

tracing:
    enable: no
    output_format: 0
    selector: 1
    start: 0
    end: -1

autocounter:
    read_rate: 0

workload:
    workload_name: bw-test-two-instances.json
    terminate_on_completion: no
    suffix_tag: null

host_debug:
    zero_out_dram: no
    disable_synth_asserts: no

synth_print:
    start: 0
    end: -1
    cycle_prefix: yes
