run_farm:
    run_farm_tag: linuxpoweroffnic
    f1_16xlarges: 1
    m4_16xlarges: 0
    f1_4xlarges: 0
    f1_2xlarges: 0
    run_instance_market: ondemand
    spot_interruption_behavior: terminate
    spot_max_price: ondemand

target_config:
    topology: example_8config
    no_net_num_nodes: 2
    link_latency: 6405
    switching_latency: 10
    net_bandwidth: 200
    profile_interval: -1
    default_hw_config: firesim_rocket_quadcore_nic_l2_llc4mb_ddr3

tracing:
    enable: no
    output_format: 0
    selector: 1
    start: 0
    end: -1

autocounter:
    read_rate: 0

workload:
    workload_name: linux-poweroff-uniform.json
    terminate_on_completion: no
    suffix_tag: null

host_debug:
    zero_out_dram: no
    disable_synth_asserts: no

synth_print:
    start: 0
    end: -1
    cycle_prefix: yes
