run_farm: aws_ec2_f1_run_farm

target_config:
    topology: no_net_config
    no_net_num_nodes: 10
    # These are unused
    link_latency: 6405
    switching_latency: 10
    net_bandwidth: 200
    profile_interval: -1
    default_hw_config: firesim_quadcore_no_nic_l2_llc4mb_ddr3

tracing:
    enable: no
    output_format: 0
    selector: 1
    start: 0
    end: -1

autocounter:
    read_rate: 0

workload:
    workload_name: spec17-intrate.json
    terminate_on_completion: yes
    suffix_tag: null

host_debug:
    zero_out_dram: no
    disable_synth_asserts: no

synth_print:
    start: 0
    end: -1
    cycle_prefix: yes
