run-farm:
    run-farm-tag: intspeed-runfarm
    f1_16xlarges: 0
    m4_16xlarges: 0
    f1_4xlarges: 0
    f1_2xlarges: 11
    run-instance-market: ondemand
    spot-interruption-behavior: terminate
    spot-max-price: ondemand

target-config:
    topology: no_net_config
    no-net-num-nodes: 11
    link-latency: 6405
    switching-latency: 10
    net-bandwidth: 200
    profile-interval: -1
    default-hw-config: firesim-quadcore-no-nic-l2-llc4mb-ddr3

tracing:
    enable: no
    output-format: 0
    selector: 1
    start: 0
    end: -1

autocounter:
    read-rate: 0

workload:
    workload-name: spec17-intspeed.json
    terminate-on-completion: no
    suffix-tag: null

host-debug:
    zero-out-dram: no
    disable-synth-asserts: no

synth-print:
    start: 0
    end: -1
    cycle-prefix: yes
