name: build-scala-doc
description: "Compiles Scala Doc"

runs:
  using: "composite"
  steps:
    - run: |
        cat env.sh
        conda info
        conda info --base
        cat $(conda info --base)/etc/profile.d/conda.sh
        conda activate --help >& /dev/null
        source env.sh
        which conda
        source env.sh && make -C sim scaladoc
      shell: bash
