# Unmanaged list of run farm hosts. Assumed that they are pre-setup to run simulations.
run_farm_type: ExternallyProvisioned
args:
    # REQUIRED: defaults used for all run farm hosts
    default_num_fpgas: 4
    default_platform: EC2InstanceDeployManager
    default_simulation_dir: /home/centos
    # REQUIRED: List of unique hostnames. Each can have multiple OPTIONAL
    # arguments, called "override_*", corresponding to the "default_*" arguments specified
    # above. Each "override_*" argument overrides the corresponding "default_*" argument for
    # that specific run host.
    #
    # Ex:
    # run_farm_hosts:
    #     # use localhost and don't override the defaults
    #     - localhost
    #     # use other IP address (don't override the defaults)
    #     - "111.111.1.111"
    #     # use other IP address (override default sim dir and num fpgas for this build host)
    #     - "222.222.2.222":
    #         override_simulation_dir: /scratch/specific-build-host-build-dir
    #         override_num_fpgas: 2
    run_farm_hosts:
        - localhost
