testing-build-farm:
    build-farm-type: aws-ec2
    args:
        instance-type: INVALID_INST_TYPE
        build-instance-market: ondemand
        spot-interruption-behavior: terminate
        spot-max-price: ondemand
        build-dir: null
