name: firesim-publish-scala-doc

on:
  push:
    branches:
      - main
    tags:
      - '[0-9]*.[0-9]*.[0-9]*'

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  AWS-ACCESS-KEY-ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS-SECRET-ACCESS-KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS-DEFAULT-REGION: ${{ secrets.AWS_DEFAULT_REGION }}
  FIRESIM_PEM: ${{ secrets.FIRESIM_PEM }}
  FIRESIM-REPO-DEP-KEY: ${{ secrets.FIRESIM_REPO_DEP_KEY }}
  LANG: "en_US.UTF-8" # required by SBT when it sees boost directories
  LANGUAGE: "en_US:en"
  LC_ALL: "en_US.UTF-8"

jobs:
  publish-scala-doc:
    name: publish-scala-doc
    runs-on: ubuntu-18.04
    container:
      image: firesim/firesim-ci:v1.3
      options: --entrypoint /bin/bash
      env:
        JVM_MEMORY: 3500M # Default JVM maximum heap limit
    steps:
      - run: |
          sudo yum -y remove git git224 git224-core ius-release.noarch # remove any older git versions and collateral first from docker image
          sudo yum -y install https://repo.ius.io/ius-release-el7.rpm6 # re-install for now
          sudo yum -y install git236 # install working git version (must match machine-launch)
      - uses: actions/checkout@v2
      - uses: ./.github/actions/repo-setup
      - uses: ./.github/actions/build-scala-doc
      - uses: ./.github/actions/push-scaladoc-to-ghpages
