name: firesim-ci-process

on: [push]

jobs:
  setup-default-manager:
    name: setup-default-manager
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256-color
    steps:
      - uses: ./.github/actions/repo-setup-aws
      - name: Initialize FireSim manager
        run: |
          .github/scripts/launch-manager-instance.py
      - uses: ./.github/actions/initialize-manager
        with:
          max-runtime-hours: 10
      - uses: ./.github/actions/initial-scala-compile

  build-default-workloads:
    name: build-default-workloads
    needs: [setup-default-manager]
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256-color
    steps:
      - uses: ./.github/actions/repo-setup-aws
      - run: |
          .github/scripts/build-default-workloads.py

  run-manager-pytests:
    name: run-manager-pytests
    needs: [setup-default-manager]
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256-color
    steps:
      - uses: ./.github/actions/repo-setup-aws
      - run: |
          .github/scripts/run-manager-pytests.py

  run-test-groupA:
    name: run-test-groupA
    needs: [setup-default-manager]
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256-color
    steps:
      - uses: ./.github/actions/repo-setup-aws
      - uses: ./.github/actions/run-scala-test
        with:
          test-name: "CIGroupA"

  run-test-groupB:
    name: run-test-groupB
    needs: [run-test-groupA]
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256-color
    steps:
      - uses: ./.github/actions/repo-setup-aws
      - uses: ./.github/actions/run-scala-test
        with:
          test-name: "CIGroupB"

  run-chipyard-tests:
    name: run-chipyard-tests
    needs: [run-test-groupB]
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256-color
    steps:
      - uses: ./.github/actions/repo-setup-aws
      - uses: ./.github/actions/run-scala-test
        with:
          target-project: "firesim"
          test-package: "firesim.firesim"
          test-name: "CITests"

  run-basic-linux-poweroff:
    name: run-basic-linux-poweroff
    needs: [build-default-workloads]
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256-color
    steps:
      - uses: ./.github/actions/repo-setup-aws
      - run: |
          .github/scripts/run-linux-poweroff.py

  run-ini-api-tests:
    name: run-ini-api-tests
    needs: [setup-default-manager]
    runs-on: ubuntu-latest
    env:
      TERM: xterm-256-color
    steps:
      - uses: ./.github/actions/repo-setup-aws
      - run: |
          .github/scripts/run-ini-api-tests.py

  documentation-check:
    name: documentation-check
    runs-on: ubuntu-latest
    container:
      image: firesim/firesim-ci:v1.1
      options: --entrypoint /bin/bash --user centos
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check that documentation builds with no warnings/errors
        run: |
          sudo yum update -y
          sudo yum install -y python3-pip
          sudo pip3 install -r docs/requirements.txt
          make -C docs html
      - name: Show error log from sphinx if failed
        if: ${{ failure() }}
        run: cat /tmp/sphinx-err*.log
